### ISSUE TITLE
Can't save from gist

### ISSUE THREAD

**Issue by jorgebucaran** [maxogden/requirebin#122]
I am unable to save to a gist or private gist.

It gets stuck forever at:

<img width="1238" alt="screen shot 2017-01-23 at 12 56 23" src="https://cloud.githubusercontent.com/assets/56996/22191121/61f80732-e16b-11e6-8c71-04f0ce30b8d8.png">

I thought this could be related to https://github.com/maxogden/requirebin/issues/76, but it seems that have been fixed for more than a year.

**Comment by revolunet** [comment]
same here

**Comment by revolunet** [comment]
looks like http://gatekeeper.maxogden.com/ is down

<img width="481" alt="capture d ecran 2017-01-23 a 18 14 44" src="https://cloud.githubusercontent.com/assets/124937/22214433/d81212b0-e197-11e6-90f5-6034e77a2fe9.png">

**Comment by crixusshen** [comment]
I also met.
（http://requirebin.com/） can only be used to develop now, If you want to create gist. Then you must getting it to run locally. According to my test, once through GITHUB OAUTH, GITHUB will the callback http://gatekeeper.maxogden.com, Because it is not set up correctly Access-Control-Allow-Origin = *, So the CORS in the screenshot.

**Comment by crixusshen** [comment]
The way I run by the local has been successfully submitted to Github Gist，If there is a problem in our communication
