### ISSUE TITLE
Responsive UI bug - button group in editor

### ISSUE THREAD

**Issue by kumavis** [maxogden/requirebin#83]
![image](https://cloud.githubusercontent.com/assets/1474978/6721441/62eca950-cd8a-11e4-8d65-af7da2055e09.png)

**Comment by maxogden** [comment]
oh yea I actually tried to fix this for a minute but had no idea :)

my temp fix was to remove the 'code was edited since last run' text that used to show up there, and instead now the 'Run Code' button goes grey if you have edited the code, which I thought would be a bit more intuitive and also save space in the UI. but we should fix this too (if someone can figure it out)

**Comment by kumavis** [comment]
yeeeaaah! :fire:
